### ISSUE TITLE
User Story: Add, Remove and Edit products in Cart

### ISSUE THREAD

**Issue by MaximeJoanisse** [gabrielkarras/SOEN341#14]
* Priority: Normal
* Risk: Normal
* User Story: As a Client, I want to add, remove and edit products from my shopping cart so that I can manage my purchase

Test Description 1:  The client can add products to their shopping cart
Precondition: Client is logged-in and is in a product detail page
- [ ] Client choose the quantity from within the form
- [ ] Client clicks on "Add to Cart"
- [ ] Client should see product in their cart
Postcondition: Cart will contain the product

Test Description 2:  The client can edit and remove products from their shopping cart
Precondition: Client is logged-in, is in a product detail page and has at least 1 product in their shopping cart
- [ ] Client clicks on "Shopping Cart"
- [ ] Client clicks on product
- [ ] Client can change the quantity of the product(if it is 0, then we remove it)
- [ ] Client should see their quantities of their product changed in their shopping cart
Postcondition: Cart will show new quantities or remove product if chosen 0
